# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Base image
FROM ubuntu:latest

# Set the working directory
WORKDIR /app

# Copy the start script into the container
COPY start.sh /app/start.sh

# Make the start script executable
RUN chmod +x /app/start.sh

# Default command to run the start script
CMD ["/app/start.sh"]
